# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36507b52c2db21fa2b96db7b9a72ae81affe76d13a6516c0115e477d448e2eba9b00f7d220bb978be132589ebc1c732363690c2bc64fa573805fb39180c96cc0

test:
  secret_key_base: 939945e0657f7e653bd2789ffd284c18f0f9937047b8fc2cf1eb69ecb9b5d195b0aeeb733c9956f62293221614b62cff9e23bb1b339669fae4aba258f07b1b13

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
